name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug == true && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: inputs.debug
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref_name}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"

      - name: "[debug] Print when triggered from main"
        if: inputs.debug && github.ref_name == 'main'
        run: |
          echo I was triggered from main branch
    
      - name: Greeting
        run: |
          echo Hello, world!
